# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/luke/Documents/SHVE honour project work/SHVE updated/SHVE+ code/SHVE/SHVE"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/luke/Documents/SHVE honour project work/SHVE updated/SHVE+ code/SHVE/SHVE"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/luke/Documents/SHVE honour project work/SHVE updated/SHVE+ code/SHVE/SHVE/CMakeFiles" "/home/luke/Documents/SHVE honour project work/SHVE updated/SHVE+ code/SHVE/SHVE/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/luke/Documents/SHVE honour project work/SHVE updated/SHVE+ code/SHVE/SHVE/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SHVETest

# Build rule for target.
SHVETest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SHVETest
.PHONY : SHVETest

# fast build rule for target.
SHVETest/fast:
	$(MAKE) -f CMakeFiles/SHVETest.dir/build.make CMakeFiles/SHVETest.dir/build
.PHONY : SHVETest/fast

SHVE.o: SHVE.cpp.o

.PHONY : SHVE.o

# target to build an object file
SHVE.cpp.o:
	$(MAKE) -f CMakeFiles/SHVETest.dir/build.make CMakeFiles/SHVETest.dir/SHVE.cpp.o
.PHONY : SHVE.cpp.o

SHVE.i: SHVE.cpp.i

.PHONY : SHVE.i

# target to preprocess a source file
SHVE.cpp.i:
	$(MAKE) -f CMakeFiles/SHVETest.dir/build.make CMakeFiles/SHVETest.dir/SHVE.cpp.i
.PHONY : SHVE.cpp.i

SHVE.s: SHVE.cpp.s

.PHONY : SHVE.s

# target to generate assembly for a file
SHVE.cpp.s:
	$(MAKE) -f CMakeFiles/SHVETest.dir/build.make CMakeFiles/SHVETest.dir/SHVE.cpp.s
.PHONY : SHVE.cpp.s

packetToAttribute.o: packetToAttribute.cpp.o

.PHONY : packetToAttribute.o

# target to build an object file
packetToAttribute.cpp.o:
	$(MAKE) -f CMakeFiles/SHVETest.dir/build.make CMakeFiles/SHVETest.dir/packetToAttribute.cpp.o
.PHONY : packetToAttribute.cpp.o

packetToAttribute.i: packetToAttribute.cpp.i

.PHONY : packetToAttribute.i

# target to preprocess a source file
packetToAttribute.cpp.i:
	$(MAKE) -f CMakeFiles/SHVETest.dir/build.make CMakeFiles/SHVETest.dir/packetToAttribute.cpp.i
.PHONY : packetToAttribute.cpp.i

packetToAttribute.s: packetToAttribute.cpp.s

.PHONY : packetToAttribute.s

# target to generate assembly for a file
packetToAttribute.cpp.s:
	$(MAKE) -f CMakeFiles/SHVETest.dir/build.make CMakeFiles/SHVETest.dir/packetToAttribute.cpp.s
.PHONY : packetToAttribute.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SHVETest"
	@echo "... SHVE.o"
	@echo "... SHVE.i"
	@echo "... SHVE.s"
	@echo "... packetToAttribute.o"
	@echo "... packetToAttribute.i"
	@echo "... packetToAttribute.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

